# Initialise a new instance
---
- name: install essential tools
  apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
  with_items:
    - git
      #- ca-certificates
      #- apt-transport-https
      #- software-properties-common

- name: Add cluster_assign2 dir
  file:
      path: /home/ubuntu/cluster_assign2
      state: directory

- name: Clone git repository to home directory
  vars:
    - destination: /home/ubuntu/cluster_assign2
  git:
    repo: "https://comeonleo@bitbucket.org/comeonleo/cluster_assign2.git"
    dest: "{{ destination }}"
    version: dev
    accept_hostkey: yes
    force: yes
    recursive: no
    #key_file: ~/.ssh/nectar.key
