# Initialise a new instance
---
  - name: add database dir
    file:
        path: /database
        state: directory

  - name: install essential tools
    apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
    with_items:
      - vim
      - git
