---
  # Create mounting point
- name: Add database dir
  file:
      path: /database
      state: directory

# Mount disk
#- name: Format volume
#  command: mkfs.ext4 /dev/vdc

- name: Mount
  command: sudo mount /dev/vdc /database

## Start CouchDB
- import_tasks: tasks/install_docker.yaml

- name: Pull couchDB image
  command: sudo docker pull couchdb

- name: Start couchDB
  command: sudo docker run -d -p 5984:5984 --env COUCHDB_USER=cluster --env COUCHDB_PASSWORD=cluster12 --volume /database:/opt/couchdb/data --name couchdb-cluster couchdb
