# Resource: Using Couchbase With Docker And Deploying A Containerized NoSQL Cluster
# URL: https://www.youtube.com/watch?v=MtelW_belIA

FROM couchbase

COPY configure.sh /opt/couchbase

# run time
CMD ["/opt/couchbase/configure.sh"]
