---
- hosts: all
  sudo: yes

  tasks:
    - import_tasks: tasks/basics.yaml
    - import_tasks: tasks/install_docker.yaml

    - name: Pull couchDB image
      command: sudo docker pull couchdb

    - name: Start couchDB
      command: sudo docker run -d -p 5984:5984 --env COUCHDB_USER=cluster --env COUCHDB_PASSWORD=cluster12 --volume /database:/opt/couchdb/data --name couchdb-cluster couchdb
